---
title: "Data Acquisition"
author: "Jamila Rzayeva"
---
# Solution challenge 1
## Load libraries
```{r}
#| echo: true
library(ROpenWeatherMap)
library(tibble)
```

## Set API Key (I have to hide this)
```{r}
API_KEY = "4168e37e031c475c3ac014612bfc9564"
```

## Get weather data (as list of lists)
```{r}
#| echo: true
current_weather <- get_current_weather(API_KEY, city = "Hamburg")
```

## Create table from relevant data points
```{r}
#| echo: true
weather_data <- tibble(weather.type = current_weather$weather$main,
                       weather.subtype = current_weather$weather$description,
                       weather.temp = current_weather$main$temp,
                       weather.feels_like = current_weather$main$feels_like,
                       weather.temp_min = current_weather$main$temp_min,
                       weather.temp_max = current_weather$main$temp_max,
                       weather.pressure = current_weather$main$pressure,
                       weather.humidity = current_weather$main$humidity,
                       wind.speed = current_weather$wind$speed,
                       wind.degree = current_weather$wind$deg)
```

## Display table
```{r}
#| echo: true
weather_data
```

# Solution challenge 2

## Load libraries
```{r}
#| echo: true
library(tidyverse)
library(glue)
library(rvest)
```

## Get bike category links
```{r}
#| echo: true
url_home <- "https://www.rosebikes.de/fahrräder"
html_home <- read_html(url_home)
bike_cats <- html_home %>%
  html_nodes(css = ".catalog-navigation__link")
links <- sapply(bike_cats, function(x) {x %>% html_attr("href")})
links <- links[1:9] %>%
  enframe(name = "position", value = "subdirectory") %>%
  mutate(
    url = glue("https://www.rosebikes.de{subdirectory}"))  %>%
  distinct(url)
```

## Define function to scrape relevant data points
```{r}
#| echo: true
get_data <- function(url) {
  html_bike_cat <- read_html(url)
  
  listings <- html_nodes(html_bike_cat, css = '.catalog-category-bikes__price-title') %>% 
    html_text(trim=TRUE) %>%              
    str_replace_all(" ","") %>%
    str_replace_all("ab", "") %>%
    str_replace_all("€", "") %>%
    str_replace_all("\n", "") %>%
    str_replace_all("\\.", "") %>%
    str_replace_all(",", "\\.") %>%
    iconv('utf-8', 'ascii', sub='') %>%
    as.numeric()
  
  names <- html_nodes(html_bike_cat, xpath = '//basic-headline/h4') %>% 
    html_text() %>%
    str_replace_all("\n", "") %>%
    str_to_title()
  
  categories <- rep(url %>% str_replace_all("https://www.rosebikes.de/fahrräder/", ""), 
              each=length(names)) %>%
    str_to_title()
  
  return(list("listings" = listings, "names" = names, "categories" = categories))
}
```
## Create table from relevant data points
```{r}
#| echo: true
data <- get_data(links$url[1])
bike_data <- tibble(bike.type = data$categories,
                    bike.name = data$names,
                    bike.price = as.numeric(data$listings))
for (i in 2:9) {
  data <- get_data(links$url[i])
  
  bike_data <- bike_data %>% add_row(bike.type = data$categories,
                                     bike.name = data$names,
                                     bike.price = as.numeric(data$listings))
}
```

## Display table
```{r}
#| echo: true
head(bike_data, 10)
```

